# ===============================
# APPLICATION
# ===============================
spring.application.name=adminservice
server.port=8084

# ===============================
# EUREKA
# ===============================
eureka.client.service-url.defaultZone=${EUREKA_URL}
eureka.instance.prefer-ip-address=true

# ===============================
# DATABASE
# ===============================
spring.datasource.url=${DB_ADMIN_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.jdbc.batch_size=20
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

# ===============================
# SECURITY
# ===============================
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}
internal.secret=${INTERNAL_SECRET}

# ===============================
# REDIS
# ===============================
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.cache.type=redis

# ===============================
# RABBITMQ
# ===============================
spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=${RABBITMQ_PORT}
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}

# ===============================
# OBSERVABILITY
# ===============================
management.tracing.sampling.probability=${TRACING_SAMPLE_RATE}
management.zipkin.tracing.endpoint=${ZIPKIN_URL}/api/v2/spans

management.endpoints.web.exposure.include=health,info,metrics,prometheus,caches,loggers
management.endpoint.prometheus.access=unrestricted
management.endpoint.health.show-details=always
management.metrics.tags.application=${spring.application.name}

# ===============================
# LOGGING
# ===============================
loki.url=${LOKI_URL}
logging.level.com.smartSure.adminService=INFO
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]
