# ===============================
# GLOBAL CONFIG (ALL SERVICES)
# ===============================

eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka}
eureka.instance.prefer-ip-address=false
eureka.instance.hostname=localhost

# Logging
logging.level.root=INFO

# Actuator
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always

# Tracing (optional global)
management.tracing.sampling.probability=${TRACING_SAMPLE_RATE:1.0}
