# ===============================
# APPLICATION
# ===============================
spring.application.name=authservice
server.port=8081

# ===============================
# DATABASE
# ===============================
spring.datasource.url=${DB_AUTH_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# ===============================
# EUREKA
# ===============================
eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka}
eureka.instance.prefer-ip-address=false
eureka.instance.hostname=localhost

# ===============================
# SECURITY
# ===============================
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:86400000}
internal.secret=${INTERNAL_SECRET}

# ===============================
# OBSERVABILITY
# ===============================
management.tracing.sampling.probability=${TRACING_SAMPLE_RATE:0.1}
management.zipkin.tracing.endpoint=${ZIPKIN_URL:http://localhost:9411}/api/v2/spans
spring.zipkin.sender.close-timeout=0

logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]

# ===============================
# PROMETHEUS
# ===============================
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.prometheus.access=unrestricted
management.endpoint.health.show-details=always

management.metrics.tags.application=${spring.application.name}
management.metrics.distribution.percentiles-histogram.http.server.requests=true

# ===============================
# LOKI
# ===============================
loki.url=${LOKI_URL:http://localhost:3100}


# Redis for OTP storage
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.cache.type=redis

# Mail for OTP sending
spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME:pramodkatchala@gmail.com}
spring.mail.password=${MAIL_PASSWORD:vttkqfymujvgobzw}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
