server.port=8081
doctor.service.message=User Auth Service is running from config file
spring.datasource.url=jdbc:mysql://localhost:3306/authservice_database
spring.datasource.username=root
spring.datasource.password=pramod280504
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
jwt.secret=767BI36HSIUNYD7352198N1SV12BS62428748NDH7878BXB7B65D326B67SBVV6VS62545265776XBHG
jwt.expiration=86400000
cors.allowed.origins=http://localhost:3000,http://localhost:4200
internal.secret=JHGUY72638DEGWRT7D4365N89SOQL89234Y3IUTBR7DT4NQ3479387DNBYFGR366746823BETYX
