# ===============================
# APPLICATION
# ===============================
spring.application.name=paymentservice
server.port=8085

# ===============================
# EUREKA
# ===============================
eureka.client.service-url.defaultZone=${EUREKA_URL}
eureka.instance.prefer-ip-address=true

# ===============================
# DATABASE
# ===============================
spring.datasource.url=${DB_PAYMENT_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# ===============================
# SECURITY
# ===============================
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}
internal.secret=${INTERNAL_SECRET}

# ===============================
# REDIS
# ===============================
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.cache.type=redis

# ===============================
# RABBITMQ
# ===============================
spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=${RABBITMQ_PORT}
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}

# ===============================
# RAZORPAY
# ===============================
razorpay.key.id=${RAZORPAY_KEY_ID}
razorpay.key.secret=${RAZORPAY_KEY_SECRET}

# ===============================
# OBSERVABILITY
# ===============================
management.tracing.sampling.probability=${TRACING_SAMPLE_RATE}
management.zipkin.tracing.endpoint=${ZIPKIN_URL}/api/v2/spans

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.prometheus.access=unrestricted
management.endpoint.health.show-details=always
management.metrics.tags.application=${spring.application.name}

# ===============================
# LOGGING
# ===============================
loki.url=${LOKI_URL}
logging.level.com.smartSure.paymentService=INFO
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]
